version: '3'
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=DBUserPass2021!
    restart: always
